"""empty message

Revision ID: 72877a9084ce
Revises: 3b8bf43c5b89
Create Date: 2022-06-03 22:59:46.154023

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72877a9084ce'
down_revision = '3b8bf43c5b89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('venue_id', sa.Integer(), nullable=True))
    op.drop_constraint('shows_venues_id_fkey', 'shows', type_='foreignkey')
    op.create_foreign_key(None, 'shows', 'venues', ['venue_id'], ['id'])
    op.drop_column('shows', 'venues_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('venues_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'shows', type_='foreignkey')
    op.create_foreign_key('shows_venues_id_fkey', 'shows', 'venues', ['venues_id'], ['id'])
    op.drop_column('shows', 'venue_id')
    # ### end Alembic commands ###
