"""empty message

Revision ID: 821a83a8da9e
Revises: 72877a9084ce
Create Date: 2022-06-03 23:34:45.074258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '821a83a8da9e'
down_revision = '72877a9084ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shows', 'id')
    # ### end Alembic commands ###
