"""empty message

Revision ID: 91ace23646e0
Revises: a67f5212d238
Create Date: 2022-06-07 21:02:32.758823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91ace23646e0'
down_revision = 'a67f5212d238'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('artist_shows')
    op.add_column('shows', sa.Column('artist_id', sa.Integer(), nullable=True))
    op.execute('UPDATE shows SET artist_id = 2 WHERE artist_id is NULL;')
    op.alter_column('shows', 'artist_id', nullable=False)

    op.create_foreign_key(None, 'shows', 'artists', ['artist_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shows', type_='foreignkey')
    op.drop_column('shows', 'artist_id')
    op.create_table('artist_shows',
    sa.Column('artist_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('show_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], name='artist_shows_artist_id_fkey'),
    sa.ForeignKeyConstraint(['show_id'], ['shows.id'], name='artist_shows_show_id_fkey'),
    sa.PrimaryKeyConstraint('artist_id', 'show_id', name='artist_shows_pkey')
    )
    # ### end Alembic commands ###
