"""empty message

Revision ID: ae8481012b03
Revises: 7d3761e16ce8
Create Date: 2022-06-04 18:09:44.365247

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae8481012b03'
down_revision = '7d3761e16ce8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('venue_genres',
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ),
    sa.PrimaryKeyConstraint('venue_id', 'genre_id')
    )
    op.add_column('artists', sa.Column('state_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'artists', 'states', ['state_id'], ['id'])
    op.drop_column('artists', 'state')
    op.add_column('venues', sa.Column('state_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'venues', 'states', ['state_id'], ['id'])
    op.drop_column('venues', 'state')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venues', sa.Column('state', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'venues', type_='foreignkey')
    op.drop_column('venues', 'state_id')
    op.add_column('artists', sa.Column('state', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'artists', type_='foreignkey')
    op.drop_column('artists', 'state_id')
    op.drop_table('venue_genres')
    op.drop_table('states')
    # ### end Alembic commands ###
