"""empty message

Revision ID: ff3582e03e0e
Revises: da5d3b4e145a
Create Date: 2022-06-12 05:29:36.223569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff3582e03e0e'
down_revision = 'da5d3b4e145a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venues', sa.Column('state', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venues', 'state')
    # ### end Alembic commands ###
